# Generated by Django 2.1.7 on 2019-03-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190330_2335'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='features',
            field=models.ManyToManyField(to='features.Feature'),
        ),
    ]
