# Generated by Django 2.1.7 on 2019-03-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190331_0032'),
        ('core', '0003_place_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
