# Generated by Django 2.1.7 on 2019-03-31 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
